### ISSUE TITLE
How to detect when function is running like in version 1

### ISSUE THREAD

**Issue by dragoblaztr** [Jomelo/LCDMenuLib2#27]
How do you do to know with scheduler library you suggested to know if is a function running or not? that was very useful and I can't find a function like that on these library (Task Scheduler).

thanks in advance

**Comment by Jomelo** [comment]
Hi, 
i have add two new examples:
- with simpleThread Library (nearly equal to the old functionality)
- with TaskScheduler Library

The TaskScheduler Library have a method "isEnabled()" to check if a task is enabled. The method can only be called on a task object.

if(t1.isEnabled() == true) { // ....

**Comment by dragoblaztr** [comment]
Thank you, that was so helpful.
