### ISSUE TITLE
Single menu option

### ISSUE THREAD

**Issue by paulosilver** [Jomelo/LCDMenuLib2#3]
Hello, i found that one menu single option does not work, or if the menu option with sub-menus if the last item of the menu, it does not enter de sub-menu

This works
LCDML_add         (0  , LCDML_0         , 1  , "OP1"   , NULL);
  LCDML_add         (1  , LCDML_0_1       , 1  , "1"    , NULL);                   
  LCDML_add         (2  , LCDML_0_1       , 2  , "2"    , NULL);                   
  LCDML_add         (3  , LCDML_0_1       , 3  , "3"             , NULL);
  LCDML_add         (4  , LCDML_0         , 2  , "OP2"           , NULL);

This does not work
LCDML_add         (0  , LCDML_0         , 1  , "OP1"   , NULL);
  LCDML_add         (1  , LCDML_0_1       , 1  , "1"    , NULL);                   
  LCDML_add         (2  , LCDML_0_1       , 2  , "2"    , NULL);                   
  LCDML_add         (3  , LCDML_0_1       , 3  , "3"             , NULL);

**Comment by Jomelo** [comment]
I can reproduce it and search the bug now :-)

**Comment by Jomelo** [comment]
Its fixed: 
https://github.com/Jomelo/LCDMenuLib2/releases/tag/v1.0.1
