### ISSUE TITLE
Screensaver does not work in i2c LCD example code when menu entry is removed

### ISSUE THREAD

**Issue by SeeJayDee** [Jomelo/LCDMenuLib2#31]
In the example sketch `LCDML_031_i2c_display_20x4` the screensaver function only works when bound to a menu entry.

At line 90 of `LCDML_031_i2c_display_20x4.ino` I changed:
`LCDML_add(17, LCDML_0, 6, "Screensaver", mFunc_screensaver);`
to:
`LCDML_add(17, LCDML_0, 6, "Screensaver", NULL);`
Everything else in the sketch was left as-is.

As a result, the screensaver function never runs despite the activation time having elapsed.
`LCDML.SCREEN_enable(...)` was called properly in `setup()`.
<br><br><br>

I tried to diagnose the cause of this myself but got lost amongst all the macros. >.>
<br>
Hardware: Arduino Uno R3, generic HD44780 display connected over i2c

**Comment by Jomelo** [comment]
Hello, 
i will check this tomorrow.

**Comment by Jomelo** [comment]
I fixed this bug in Version 1.3.0
