### ISSUE TITLE
Inverted def on buttons keypad

### ISSUE THREAD

**Issue by lalo-uy** [Jomelo/LCDMenuLib2#4]
If used with independent buttons (LCDML_CONTROL_cfg = 2 ), the comnent and default value are inverted

now is : 

 #define _LCDML_CONTROL_digital_low_active      0    // (0 = low active (pullup), 1 = high active (pulldown) button

shuld be: 

 #define _LCDML_CONTROL_digital_low_active      1    // (1 = low active (pullup), 0 = high active (pulldown) button

**Comment by Jomelo** [comment]
Fixed with 1.0.2
