### ISSUE TITLE
Select language during program execution

### ISSUE THREAD

**Issue by effeci** [Jomelo/LCDMenuLib2#42]
Hello! Firstable, Thanks for this beautiful library... I was tinkering with it from version one. I do like how the multilanguage is implemented, but i was wondering if it the language can be changed while using the program, like 
--->settings--->Language---->select Language;
and then going back and ... boom: language switched.
Is it possible? Thanks for the attention.

**Comment by Jomelo** [comment]
Yes it is possible with the latest version 2.1.0

In version 2.1.0 is a new example named LCDML_022_multiLanguage and some new macros. When you open this example and changed the variable from 

lang_types g_lcdml_lang_select = LANG_DE;
to 
lang_types g_lcdml_lang_select = LANG_DEFAULT;  

in your program. The language will change directly.

**Comment by effeci** [comment]
Sorry but is it possible to switch while the program is running?

**Comment by Jomelo** [comment]
yes change the variable in the program.

**Comment by Jomelo** [comment]
I add a smaller example to test it:

https://github.com/Jomelo/LCDMenuLib2/tree/master/examples/02_functionality

**Comment by effeci** [comment]
Ohhhh now I see! Vielen dank!
