### ISSUE TITLE
Unexpected behaviour of OTHER_jumpToFunc/OTHER_jumpToID

### ISSUE THREAD

**Issue by Rub3nCT** [Jomelo/LCDMenuLib2#45]
If you jump from a menu function to another (using some parameter), the value of the parameter never changes again. Tested with OTHER_jumpToFunc and OTHER_jumpToID.

[Test.zip](https://github.com/Jomelo/LCDMenuLib2/files/3188740/Test.zip)

To reproduce, follow these steps:

Enter function "Call > OK_VAL1" --> You should see:

```
[FUNCTION_OPEN] - mFunc_Call
[VALUE] - Called with: 1
[VALUE_OK] - 1
```

Long press to exit. Then enter function "Call > OK_VAL2"
```
[FUNCTION_OPEN] - mFunc_Call
[VALUE] - Called with: 2
[VALUE_OK] - 2
```

You can do this as many times as you want and it will work fine. Now let's break it...

Enter function "Call > OK_VAL1" and press Enter. This will jump to mFunc_ShowInfo without any parameter. You should see:

```
[FUNCTION_OPEN] - mFunc_Call
[VALUE] - Called with: 1
[VALUE_OK] - 1
[USER] - Enter
 > Jump to mFunc_ShowInfo
[FUNCTION_CLOSE] - mFunc_Call

[FUNCTION_OPEN] - mFunc_ShowInfo
[PARAM] - Called without value
[FUNCTION_CLOSE] - mFunc_ShowInfo
```

Now enter function "Call > OK_VAL2" and press Enter. This will jump to mFunc_ShowInfo with a parameter with a _wrong_ value. You should see:

```
[FUNCTION_OPEN] - mFunc_Call
[VALUE] - Called with: 2
[VALUE_OK] - 2
[USER] - Enter
 > Jump to mFunc_ShowInfo (with parameter BAD_VAL)
[FUNCTION_CLOSE] - mFunc_Call

[FUNCTION_OPEN] - mFunc_ShowInfo
[PARAM] - Called with: 3
[FUNCTION_CLOSE] - mFunc_ShowInfo
```

Now, "Call > OK_VAL1" and "Call > OK_VAL2" are broken. Parameter value stays with the previous _wrong_ value. Just enter any of them and you will see:

```
[FUNCTION_OPEN] - mFunc_Call
[VALUE] - Called with: 3
[VALUE_NOT_OK] - 3 (should be 1 or 2)
```

**Comment by Jomelo** [comment]
thanks for reporting. The bug is fixed in the next version
