### ISSUE TITLE
Rollover Bug

### ISSUE THREAD

**Issue by canghaiwuhen** [Jomelo/LCDMenuLib2#46]
I used 1.3 is OK, but 2.0 and 2.1 found a question.
My tft can display 16 rows, my menu only used 9, the menu can't rollover.
I debug it and changed LCDMenuLib2.cpp
if(bitRead(REG_control, _LCDML_REG_control_rollover) && rollover == true && child_cnt > window_rows)
to
if(bitRead(REG_control, _LCDML_REG_control_rollover) && rollover == true)
It  works~

**Comment by Jomelo** [comment]
Thanks for reporting the bug. I will fix the bug with the next version.

**Comment by canghaiwuhen** [comment]
> Thanks for reporting the bug. I will fix the bug with the next version.

Thanks!
