### ISSUE TITLE
Please support ESP32!

### ISSUE THREAD

**Issue by tackelua** [Jomelo/LCDMenuLib2#5]
I test with LCD_I2C
Compile with ESP32 Dev Kit and it's error
`LiquidCrystal.cpp: 190:48: error: 'analogWrite' was not declared in this scope
   analogWrite ( _backlightPin, value )`
Compiler can not found <Arduino.h> in file LiquidCrystal.cpp
`#if (ARDUINO <  100)
#include <WProgram.h>
#else
#include <Arduino.h>
#endif`
But the problem, we use LCD I2C it's mean LiquidCrystal_I2C.h but compiller also use LiquidCrystal.h

**Comment by Jomelo** [comment]
Hello, i test the library with an ESP32 and it works. 

I think you have a problem with your I2C library.  I think you have to find a new I2C library which works with an ESP32.

**Comment by Jomelo** [comment]
I remove one bug with ESP8266 and ESP32 in version 1.0.2. But i cannot find a bug in the liquidCrystal lib. This lib is written from other programers.

**Comment by tackelua** [comment]
>  I think you have to find a new I2C library which works with an ESP32.

Can you give me a link of the library that you using? Pls
Thank you!

**Comment by Jomelo** [comment]
I am currently not using any i2c displys.
