### ISSUE TITLE
Max Element in a menu

### ISSUE THREAD

**Issue by GavC666** [Jomelo/LCDMenuLib2#50]
Hi,
I'm currently in the middle of a build of a massive menu. I had 286 elements when I tried to compile however compiler fails on what I believe is the max menu elements. I'm trying to write sketch to a breadboard ATmega 1284p so no issues with memory. I can compile up to 255 element with success. Can you advise how I can add more elements? Is it as simple as redefining the relevant variable to 16bit variable? If so can you point me in the right direction.
Many thanks for sharing this Lib with the community. It is by far the best I have used in my.sketches.

**Comment by Jomelo** [comment]
Hello, 

the menu supports only 254 menu elements. When you have 286 menu entries perhaps you can optimize some elements. (for example with parameters ).

The limit of 254 cannot be changed.
