### ISSUE TITLE
Maximum buttons

### ISSUE THREAD

**Issue by Devaterus** [Jomelo/LCDMenuLib2#51]
Hi, is there any chance to increase max buttons from 6 to 20? 
I´m curently using matrix keypad 5x4 and i want to know if its possible to increase amount of buttons.

**Comment by Jomelo** [comment]
Hi, 
this feature comes with the next version 2.2.0. It is implemented on the current beta version.

**Comment by Jomelo** [comment]
This feature is now testes. The extension is for 64 events. 
Events can be used for buttons and can be combined with callback menu functions.
