### ISSUE TITLE
SAMD support

### ISSUE THREAD

**Issue by JustSomeRandomDIYGuy** [Jomelo/LCDMenuLib2#52]
Hi Jomelo, 

I've used your lib now for different projects and the most are running on SAMD21 boards like Adafruit's Feather M0. Yesterday I tried the new Feather M4 Express with the SAMD51 and it also compiles and runs without any issue. 

The only thing that disturbs a bit are the compiler warnings during compilation in Arduino IDE and the compiler aborts in Visual Micro. I can fix both by modifying your library.properties file but I guess its not necessary to exclude this architecture.

Do you think about lifting this limitation or is there some hard reason for not supporting those chips that I am not aware of?

Regards,
Marco

**Comment by Jomelo** [comment]
Hello, 
i have changed the architecture flag to "*". There is no limitation. The new version is available on master branch. 
Regards,
Nils

**Comment by JustSomeRandomDIYGuy** [comment]
Great. Thank you!
