### ISSUE TITLE
CONTROL WITH ENCODER

### ISSUE THREAD

**Issue by totza2010** [Jomelo/LCDMenuLib2#63]
CONTROL WITH ENCODER    BT_quit, BT_enter Work.
                                                BT_left, BT_down, BT_right, BT_up not work.
test from code https://github.com/PaulStoffregen/Encoder/tree/master/examples/Basic work.
![2020-05-04](https://user-images.githubusercontent.com/13436403/80986378-b0a49b80-8e5a-11ea-9e14-63d5df7ca467.png)

**Comment by Jomelo** [comment]
Hi, 
how have you connect the encoder ? With my encoder it works correct.

**Comment by totza2010** [comment]
#define encoder_A_pin       35
#define encoder_B_pin       34
#define encoder_button_pin  36

i use esp32

**Comment by Jomelo** [comment]
I read the ESP32 datasheet for you:
https://randomnerdtutorials.com/esp32-pinout-reference-gpios/

> Input only pins
> GPIOs 34 to 39 are GPIs – input only pins. These pins don’t have internal pull-ups or pull-down resistors. They can’t be used as outputs, so use these pins only as inputs:
> 
> GPIO 34
> GPIO 35
> GPIO 36
> GPIO 39

You have to add extern pullup resistors.

**Comment by Jomelo** [comment]
Is this problem fixed with extern pullups ?
