### ISSUE TITLE
I don't understand how to use this Library (u8glib)?

### ISSUE THREAD

**Issue by tobiashochguertel** [Jomelo/LCDMenuLib2#7]
I search a way to create a Menu, I saw your example picture which use u8glib [http://jomelo.de/r/arduino/images/graphic_lcd_1.jpg](http://jomelo.de/r/arduino/images/graphic_lcd_1.jpg)

Can you provide a example code to use this library with u8glib?

**Comment by Jomelo** [comment]
Hi, 
the image is created with first version of the library: 
https://github.com/Jomelo/LCDMenuLib

I will create the u8glib example soon.

**Comment by Jomelo** [comment]
I add an example for the u8glib

**Comment by tobiashochguertel** [comment]
Thanks! Cool that I can control the menu via serial monitor :)

👍
