### ISSUE TITLE
does this menu support rotation encoder?

### ISSUE THREAD

**Issue by youxiaojie** [Jomelo/LCDMenuLib2#75]
does this menu support rotation encoder?
I see it support 3 to 6 buttons, not mentioned encoder, so I ask here. 
thanx

**Comment by Jomelo** [comment]
Hello, 
yes it is possible. Open any example and navigate to the LCDML_control tab and read the comments:

Chose Option 3

// content:
// (0) Control over serial interface  with asdw_e_q
// (1) Control over one analog input
// (2) Control over 4 - 6 digital input pins (internal pullups enabled)
**// (3) Control over encoder [third party lib] (Download: https://github.com/PaulStoffregen/Encoder)**
// (4) Control with Keypad  [third party lib] (Download: http://playground.arduino.cc/Main/KeypadTutorial )
// (5) Control with an IRMP remote [third party lib] (Download: https://github.com/ukw100/IRMP )
// (6) Control with a joystick
// (7) Control over I2C PCF8574

Scroll down until you find the code (line 243) for option 3 and read the comments. Adapt your pins to the example and use it ,-)

You have to download the encoder lib from PaulStoffregen. You can find the link in the comments.
