### ISSUE TITLE
wrong variable used in LCDML_control ?

### ISSUE THREAD

**Issue by AndiRuss** [Jomelo/LCDMenuLib2#9]
Line 238:
// check encoder status and set control menu
  if (!a && g_LCDML_CONTROL_encoder_a_prev) {
    **g_LCDML_CONTROL_encoder_t_prev = 1;**

I assume following is wrong 
    **g_LCDML_CONTROL_encoder_t_prev = 1;** 
better
    **g_LCDML_CONTROL_encoder_a_prev = 1;**

**Comment by Jomelo** [comment]
In the newer version this code is rewritten
